version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "9000:9000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_URL=${DB_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - .:/app
